version: '3.7'

#####################################################
# This Docker Compose file contains two services
#    Dependency-Track API Server
#    Dependency-Track FrontEnd
#####################################################

volumes:
  dependency-track:
  jenkins-vol:

services:
  dtrack-apiserver:
    image: dependencytrack/apiserver
    ports:
      - '8081:8080'
    volumes:
      - 'dependency-track:/data'

  dtrack-frontend:
    image: dependencytrack/frontend
    depends_on:
      - dtrack-apiserver
    environment:
      - API_BASE_URL=http://51.17.167.230:8081
    ports:
      - "8082:8080"
  
  jenkins:
    image: jenkins/jenkins:jdk11
    ports:
      - '8080:8080'
    volumes:
      - 'jenkins-vol:/var/jenkins_home'
